// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getEvents() : Promise<Result<EventDetail[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_events") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getUpcomingEvents() : Promise<Result<UpcomingEvent[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_upcoming_events") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEvent(eventId: number) : Promise<Result<EventDetail | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_event", { eventId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getArtistContext(eventId: number, eventDate: string) : Promise<Result<ArtistContextSet[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_artist_context", { eventId, eventDate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createEvent(input: CreateEventInput) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_event", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateEvent(eventId: number, input: CreateEventInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_event", { eventId, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle b2b linkage between artist at `index` and the one before it.
 * Returns the updated artist list with corrected set_groups.
 */
async toggleB2b(artists: ArtistEntry[], index: number) : Promise<ArtistEntry[]> {
    return await TAURI_INVOKE("toggle_b2b", { artists, index });
},
async setEventCancelled(eventId: number, cancelled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_event_cancelled", { eventId, cancelled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteEvent(eventId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_event", { eventId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getArtists() : Promise<Result<ArtistWithCount[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_artists") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getArtistTagCounts() : Promise<Result<TagCount[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_artist_tag_counts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getArtistStats(artistId: number) : Promise<Result<ArtistStats, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_artist_stats", { artistId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getVenues() : Promise<Result<VenueWithCount[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_venues") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getVenueAutocomplete() : Promise<Result<VenueAutocompleteEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_venue_autocomplete") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLocations() : Promise<Result<LocationWithCount[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_locations") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFriends() : Promise<Result<FriendWithCount[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_friends") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a standalone friend not tied to any event. Find-or-create semantics:
 * re-adding an existing name (case-insensitively) is a no-op that returns the
 * existing id rather than erroring on the UNIQUE constraint. Returns the id.
 */
async createFriend(name: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_friend", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEventsForArtist(artistId: number, sortKey: EventSortKey | null, sortDir: SortDir | null) : Promise<Result<EventDetail[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_events_for_artist", { artistId, sortKey, sortDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEventsForVenue(venueId: number, sortKey: EventSortKey | null, sortDir: SortDir | null) : Promise<Result<EventDetail[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_events_for_venue", { venueId, sortKey, sortDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEventsForLocation(locationId: number, sortKey: EventSortKey | null, sortDir: SortDir | null) : Promise<Result<EventDetail[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_events_for_location", { locationId, sortKey, sortDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEventsForFriend(friendId: number, sortKey: EventSortKey | null, sortDir: SortDir | null) : Promise<Result<EventDetail[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_events_for_friend", { friendId, sortKey, sortDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getArtistEventNames() : Promise<Result<EntityEventNames[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_artist_event_names") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getVenueEventNames() : Promise<Result<EntityEventNames[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_venue_event_names") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLocationEventNames() : Promise<Result<EntityEventNames[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_location_event_names") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFriendEventNames() : Promise<Result<EntityEventNames[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_friend_event_names") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async queryEvents(input: EventsQueryInput) : Promise<Result<EventDetail[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("query_events", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async queryArtists(input: ArtistsQueryInput) : Promise<Result<ArtistWithCount[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("query_artists", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async queryVenues(input: VenuesQueryInput) : Promise<Result<VenueWithCount[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("query_venues", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async queryLocations(input: LocationsQueryInput) : Promise<Result<LocationWithCount[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("query_locations", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async queryFriends(input: FriendsQueryInput) : Promise<Result<FriendWithCount[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("query_friends", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameArtist(artistId: number, name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_artist", { artistId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameVenue(venueId: number, name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_venue", { venueId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameLocation(locationId: number, city: string, state: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_location", { locationId, city, state }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameFriend(friendId: number, name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_friend", { friendId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mergeArtists(keepId: number, mergeId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("merge_artists", { keepId, mergeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mergeVenues(keepId: number, mergeId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("merge_venues", { keepId, mergeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mergeLocations(keepId: number, mergeId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("merge_locations", { keepId, mergeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteVenue(venueId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_venue", { venueId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteArtist(artistId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_artist", { artistId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteLocation(locationId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_location", { locationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteFriend(friendId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_friend", { friendId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getStats() : Promise<Result<Stats, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Legacy one-shot import — parses and writes in one call with no row-level
 * filtering. Now a thin wrapper over `run_import` so the write loop lives in
 * one place. Kept so any external caller (or future bulk path) still has the
 * "import everything" entry point.
 */
async importCsv(csvContent: string) : Promise<Result<ImportResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_csv", { csvContent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read-only classification of every CSV row. No writes, no side effects.
 * Preview checks duplicates and venue conflicts against the live database
 * so the user sees the same outcome they'd get on commit — minus races from
 * concurrent writes, which are re-caught on the actual import.
 */
async previewCsvImport(csvContent: string) : Promise<Result<PreviewRow[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_csv_import", { csvContent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Filtered import — run the write path, but only for rows whose index is in
 * `selected_indices`. Unselected rows are silently skipped (not counted as
 * `events_skipped`; that counter is reserved for duplicates detected during
 * the write).
 */
async importCsvFiltered(csvContent: string, selectedIndices: number[]) : Promise<Result<ImportResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_csv_filtered", { csvContent, selectedIndices }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export all events as CSV to a file. B2b artists are joined with " b2b ".
 */
async exportCsv(destination: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_csv", { destination }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async backupDatabase(destination: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("backup_database", { destination }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restoreDatabase(source: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_database", { source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch metadata from MusicBrainz for all artists that haven't been looked up yet.
 */
async fetchGenres() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_genres") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hasSetlistfmKey() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_setlistfm_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check cache only — no API call. Returns None if not cached.
 */
async getCachedSetlist(artistMbid: string, date: string) : Promise<Result<SetlistResult | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cached_setlist", { artistMbid, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch setlist from API (with cache check first).
 */
async getSetlist(artistMbid: string, date: string) : Promise<Result<SetlistResult | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_setlist", { artistMbid, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear all metadata and set mbid to "skip" so the fetcher ignores this artist.
 */
async clearArtistMetadata(artistId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_artist_metadata", { artistId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get external links for an artist. Returns from DB if cached,
 * otherwise fetches from MusicBrainz using the stored mbid and saves.
 */
async getArtistLinks(artistId: number) : Promise<Result<ArtistLinks | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_artist_links", { artistId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Search MusicBrainz for multiple artist matches.
 */
async searchMusicbrainz(artistName: string, limit: number | null) : Promise<Result<MusicBrainzMatch[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_musicbrainz", { artistName, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch full metadata for a specific MusicBrainz artist by ID and save to our DB.
 */
async applyMusicbrainzMatch(artistId: number, mbid: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_musicbrainz_match", { artistId, mbid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The artist's current curated tags.
 */
async getArtistTags(artistId: number) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_artist_tags", { artistId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save a tag onto an artist. Normalized + idempotent (see `db::tags`).
 */
async addArtistTag(artistId: number, tag: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_artist_tag", { artistId, tag }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a tag from an artist.
 */
async removeArtistTag(artistId: number, tag: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_artist_tag", { artistId, tag }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pull tag *suggestions* for an artist from MusicBrainz. Prefers an exact
 * lookup by the stored MBID; falls back to a name search. Returns the
 * folksonomy tags sorted by vote count. Writes nothing — the user decides
 * which to save via `add_artist_tag`.
 */
async suggestArtistTags(artistId: number) : Promise<Result<TagSuggestion[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suggest_artist_tags", { artistId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Artists in the collection that share tags with this one, ranked by overlap.
 */
async getSimilarArtistsByTags(artistId: number) : Promise<Result<SimilarArtist[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_similar_artists_by_tags", { artistId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The common-tags suggestion pool (seeded common genres + anything you added).
 */
async getCommonTags() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_common_tags") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a tag to the common-tags pool.
 */
async addCommonTag(tag: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_common_tag", { tag }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a tag from the common-tags pool (leaves applied tags untouched).
 */
async removeCommonTag(tag: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_common_tag", { tag }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addEventMedia(eventId: number, sourcePath: string) : Promise<Result<EventMedia, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_event_media", { eventId, sourcePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEventMedia(eventId: number) : Promise<Result<EventMedia[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_event_media", { eventId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMediaForEvents(eventIds: number[]) : Promise<Result<EventMedia[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_media_for_events", { eventIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every media item across every event, for the top-level Media tab. Shares
 * `get_media_for_events`'s JOIN shape (event name + date populated), and
 * matches its sort so the Media tab groups naturally by event in the same
 * order per-event galleries render internally. Intentionally unpaginated —
 * a personal tracker with a few hundred items renders fine, and streaming
 * adds complexity we don't need yet.
 */
async getAllMedia() : Promise<Result<EventMedia[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_media") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Photo/video totals for the Media page tab strip. One query in Rust is
 * dramatically less traffic than shipping every media row to the frontend
 * just to count them — and the classification rule (`video/*` mime) lives
 * in exactly one place now.
 */
async getMediaCounts() : Promise<Result<MediaCounts, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_media_counts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteEventMedia(mediaId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_event_media", { mediaId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateEventMediaCaption(mediaId: number, caption: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_event_media_caption", { mediaId, caption }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async wipeDatabase() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wipe_database") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the highest applied schema migration version. This is the database
 * version, distinct from the app version — useful for surfacing in the UI so
 * users (and bug reports) can pinpoint which schema they're on.
 */
async getDbVersion() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_db_version") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getChangelog() : Promise<ChangelogEntry[]> {
    return await TAURI_INVOKE("get_changelog");
},
async getSetting(key: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSetting(key: string, value: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_setting", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Build a full accent definition from a user-picked hex color. The hex drives
 * --primary directly (a valid CSS color) for both themes, with a foreground
 * chosen for contrast. The id derives from the hex so re-adding the same color
 * de-dupes instead of stacking.
 */
async makeCustomAccent(hex: string) : Promise<AccentPreset> {
    return await TAURI_INVOKE("make_custom_accent", { hex });
},
async fetchUpdate() : Promise<Result<UpdateMetadata | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installUpdate(onEvent: TAURI_CHANNEL<DownloadEvent>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_update", { onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AccentColors = { primary: string; primaryForeground: string }
export type AccentPreset = { id: string; label: string; swatch: string; light: AccentColors; dark: AccentColors }
/**
 * Enriched artist info for event detail view — includes attendance context.
 */
export type ArtistContext = { id: number; name: string; set_group: number | null; total_events: number; first_event: boolean; mbid: string | null }
export type ArtistContextSet = { artists: ArtistContext[] }
export type ArtistEntry = { 
/**
 * Id of an existing artist when this chip came from a known artist, so the
 * save links by it instead of re-resolving the (display) name — the same
 * id-over-name rule the friend chips use. `None` is a freshly typed name,
 * resolved via find-or-create (and counted as new for the MusicBrainz
 * metadata fetch). `toggle_b2b` only reshuffles set_group, so it carries
 * the id straight through.
 */
id: number | null; name: string; set_group: number | null }
export type ArtistInfo = { id: number; name: string; set_group: number | null }
export type ArtistLinks = { link_spotify: string | null; link_instagram: string | null; link_youtube: string | null; link_soundcloud: string | null; link_bandcamp: string | null; link_website: string | null }
/**
 * A group of artists that perform together (b2b). Solo artists are a set of one.
 */
export type ArtistSet = { artists: ArtistInfo[] }
/**
 * Detailed stats for a single artist.
 */
export type ArtistStats = { genre: string | null; tags: string | null; country: string | null; artist_type: string | null; begin_year: string | null; end_year: string | null; active: boolean | null; disambiguation: string | null; first_seen: string | null; last_seen: string | null; unique_venues: number; unique_locations: number; related_artists: RelatedArtist[] }
/**
 * `tags` is a cleaned list (trimmed, non-empty) rather than the raw CSV so
 * the frontend can filter and render without re-parsing. Source-agnostic —
 * see `db::tags` for the future custom-tag merge point.
 */
export type ArtistWithCount = { id: number; name: string; event_count: number; genre: string | null; country: string | null; artist_type: string | null; tags: string[] }
export type ArtistsQueryInput = { query?: string | null; 
/**
 * Optional tag filter with OR semantics — an artist matches if *any*
 * of its tags appears in this set. Callers may pass mixed-case values;
 * we lowercase them here for the comparison.
 */
tags?: string[] | null; sortKey?: EntitySortKey | null; sortDir?: SortDir | null; limit?: number | null }
export type ChangelogEntry = { 
/**
 * e.g. "v1.1.1".
 */
version: string; 
/**
 * ISO date from the heading, when present.
 */
date: string | null; sections: ChangelogSection[] }
export type ChangelogSection = { 
/**
 * "Features", "Fixes", … — empty for bullets that precede any `###` head.
 */
title: string; items: string[] }
export type CreateEventInput = { name: string; date: string; end_date: string | null; notes: string | null; venue: string; city: string; state: string; artists: ArtistEntry[]; 
/**
 * Friends who attended. Existing friends carry their `id` and link by it;
 * newly typed friends have `id: None` and are resolved by name
 * (find-or-create) on the way in. No set_group — friends have no b2b
 * concept. See [`FriendEntry`] for why the id matters under Streamer Mode.
 */
friends: FriendEntry[] }
/**
 * Adjacently-tagged so the frontend can discriminate on `event` and get a
 * typed `data` payload. Kept in sync with the `useUpdater` hook's switch on
 * `event.event`.
 */
export type DownloadEvent = { event: "Started"; data: { contentLength: number | null } } | { event: "Progress"; data: { chunkLength: number } } | { event: "Finished" }
export type EntityCount = { id: number; name: string; count: number }
/**
 * Per-entity list of event names used only by the list-page tooltip bars.
 * Aggregated in Rust so the frontend doesn't have to pull every event just
 * to walk the relationships itself — see `queries::get_*_event_names`.
 */
export type EntityEventNames = { id: number; names: string[] }
/**
 * Artists, venues, and locations all sort by the same two axes: their
 * "natural" display name or the per-entity event count. The per-entity
 * meaning of `Name` differs (venue strips "The ", locations compose
 * "state, city"), but the enum variants line up.
 */
export type EntitySortKey = "name" | "count"
/**
 * Event with all related data joined — used for list and detail views.
 */
export type EventDetail = { id: number; name: string; date: string; end_date: string | null; notes: string | null; cancelled: boolean; venue: string; city: string; state: string; artist_sets: ArtistSet[]; friends: Friend[]; venue_id: number; location_id: number }
/**
 * Structured, faceted event filter. Each populated facet ANDs with the rest;
 * an empty facet imposes no constraint. The friend/artist facets match by id
 * and use `*_match` to pick AND vs OR *within* that facet; the text facets are
 * case-insensitive substring matches against a single field.
 * 
 * Faceted by design: facets only ever combine with AND — there is no
 * cross-facet OR (e.g. "friend Alice OR artist X"). That was the deliberate
 * trade for a predictable builder UI. The predicates are kept flat and
 * independent so a future grouped/boolean model could compose these same
 * helpers without rewriting them.
 */
export type EventFilter = { friendIds?: number[]; friendsMatch?: MatchMode | null; artistIds?: number[]; artistsMatch?: MatchMode | null; name?: string | null; venue?: string | null; city?: string | null; state?: string | null }
/**
 * Media row with its computed absolute filesystem path, ready to be wrapped
 * by the frontend's `convertFileSrc`. `event_name` / `event_date` are
 * populated by the bulk query for cross-entity galleries; on single-event
 * fetches they are left empty.
 */
export type EventMedia = { id: number; event_id: number; filename: string; mime_type: string; file_size: number; caption: string | null; created_at: string; captured_at: string | null; absolute_path: string; event_name: string | null; event_date: string | null }
export type EventSortKey = "date" | "name" | "venue" | "location"
export type EventsQueryInput = { query?: string | null; 
/**
 * Structured facets, ANDed on top of the free-text `query`.
 */
filter?: EventFilter | null; sortKey?: EventSortKey | null; sortDir?: SortDir | null; limit?: number | null }
/**
 * A friend you attended an event with. Deliberately minimal (id + name) —
 * friends have none of the metadata artists accumulate. Carried inline on
 * `EventDetail` so the event form can prefill the chips synchronously.
 */
export type Friend = { id: number; name: string }
export type FriendEntry = { 
/**
 * Id of an existing friend when this chip came from a known friend. The
 * save links by this id and *ignores* `name`, which is what lets Streamer
 * Mode hand back first-name-only display names without a masked "Sarah"
 * being resolved to a brand-new duplicate friend. `None` means a freshly
 * typed name, resolved via find-or-create.
 */
id: number | null; name: string }
export type FriendWithCount = { id: number; name: string; event_count: number }
export type FriendsQueryInput = { query?: string | null; sortKey?: EntitySortKey | null; sortDir?: SortDir | null; limit?: number | null }
/**
 * A single row for the Top Genres radar chart. Genres don't have DB ids
 * — they're derived from comma-split `artists.tags` values — so this uses
 * a dedicated struct instead of piggy-backing on `EntityCount`.
 */
export type GenreCount = { name: string; count: number }
/**
 * Result of a CSV import operation.
 */
export type ImportResult = { events_created: number; events_skipped: number; artists_created: number; venues_created: number; locations_created: number }
export type LocationWithCount = { id: number; city: string; state: string; event_count: number }
export type LocationsQueryInput = { query?: string | null; sortKey?: EntitySortKey | null; sortDir?: SortDir | null; limit?: number | null }
/**
 * Within a multi-value facet (friends, artists), choose whether the event
 * must include *every* selected value (`All` → AND) or *at least one*
 * (`Any` → OR).
 */
export type MatchMode = "all" | "any"
/**
 * Photo/video counts for the Media page tab strip. Kept as a tiny
 * dedicated shape rather than returning a generic map so serde generates
 * a nice TS interface without a `Record<string, number>`.
 */
export type MediaCounts = { all: number; photos: number; videos: number }
export type MonthCount = { month: string; count: number }
export type MusicBrainzMatch = { mbid: string; name: string; score: number; disambiguation: string; artist_type: string; country: string; begin_year: string }
/**
 * A single CSV row after parsing — no database interaction. Shared by the
 * preview and import paths so field-level parsing lives in exactly one place.
 * `parse_error` is populated when the row fails validation; rows with errors
 * are still surfaced to the UI so the user can see what went wrong, but they
 * can't be checked in the preview dialog.
 */
export type ParsedRow = { row_index: number; date: string | null; end_date: string | null; event_name: string; venue_name: string; city: string; state: string; 
/**
 * Each inner `Vec` is one comma-separated entry from the CSV, already
 * split on " b2b ". Single-artist entries are length-1 sets; b2b entries
 * are length-N sets that import as one `set_group`. The preview UI
 * flattens this for display, but the write path uses the groups as-is
 * so b2b info from the CSV survives round-trip.
 */
artist_groups: string[][]; parse_error: string | null }
export type PreviewRow = { row: ParsedRow; status: PreviewStatus }
/**
 * Per-row preview classification. `VenueConflict` carries the existing
 * location so the UI can tell the user exactly which other city claims the
 * venue name.
 */
export type PreviewStatus = { kind: "Ok" } | { kind: "Duplicate" } | { kind: "VenueConflict"; existing_location: string } | { kind: "ParseError"; message: string }
export type RelatedArtist = { id: number; name: string; shared_events: number }
export type SetlistResult = { event_date: string; venue_name: string; city: string; songs: SetlistSong[]; url: string }
export type SetlistSong = { name: string; info: string | null; tape: boolean }
/**
 * An artist suggested by tag overlap (shares ≥1 curated tag with the subject
 * artist). `shared_tags` drives the ranking; `event_count` is how many shows
 * of theirs you've logged, shown alongside the name.
 */
export type SimilarArtist = { id: number; name: string; shared_tags: number; event_count: number }
export type SortDir = "asc" | "desc"
/**
 * Stats summary for the dashboard.
 */
export type Stats = { total_events: number; total_artists: number; total_venues: number; total_locations: number; top_artists: EntityCount[]; top_venues: EntityCount[]; 
/**
 * Friends you've attended the most events with. Standalone friends (zero
 * events) are excluded — the inner join drops them.
 */
top_friends: EntityCount[]; events_per_year: YearCount[]; events_per_month: MonthCount[]; 
/**
 * Aggregated from each artist's curated tags, counted by distinct attended
 * events per tag. Empty until some artists have tags — the UI then hints at
 * adding tags on the artist pages.
 */
top_genres: GenreCount[] }
export type TAURI_CHANNEL<TSend> = null
/**
 * Aggregated tag chip data for the Artists list filter strip. `key` is the
 * lowercased form used for matching (matches the URL query param and the
 * `query_artists` tag filter). `display` is the first-seen casing — same
 * policy as the top-genres aggregator. `count` is the number of distinct
 * artists that carry this tag.
 */
export type TagCount = { key: string; display: string; count: number }
/**
 * A candidate tag offered by MusicBrainz, with its community vote count so the
 * UI can surface the most-agreed-upon tags first. Suggestions are never
 * written to the DB on their own — the user clicks the ones they want.
 */
export type TagSuggestion = { name: string; count: number }
/**
 * A not-yet-attended event plus the relative-time value used by the
 * dashboard. Wrapping `EventDetail` (rather than adding a `days_until`
 * field to it) keeps the main shape clean — "days until" is only
 * meaningful for upcoming rows.
 * 
 * `days_until` is a signed count of calendar days from today (local) to
 * the event date. Zero means today, one means tomorrow. The frontend
 * owns the eventual string label so i18n stays on the display side.
 */
export type UpcomingEvent = { event: EventDetail; days_until: number }
export type UpdateMetadata = { version: string; currentVersion: string }
/**
 * A venue name grouped with the list of locations that name appears at.
 * Case-insensitive deduplication happens server-side so the EventForm
 * autocomplete doesn't re-implement the rule in TypeScript. `display_name`
 * is the first-seen casing, mirroring the policy used by the top-genres
 * aggregator.
 */
export type VenueAutocompleteEntry = { display_name: string; locations: VenueLocation[] }
export type VenueLocation = { city: string; state: string }
/**
 * Venues need location context in list views since the same name can exist in
 * different cities (e.g., "The Independent" in SF vs Austin).
 */
export type VenueWithCount = { id: number; name: string; event_count: number; location_id: number; city: string; state: string }
export type VenuesQueryInput = { query?: string | null; sortKey?: EntitySortKey | null; sortDir?: SortDir | null; limit?: number | null }
export type YearCount = { year: string; count: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
